#!/usr/bin/env bash
# bash script to nginx on server
sudo apt-get -y update && sudo apt-get install -y nginx

echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx start
