#!/usr/bin/env bash
# bash script to install nginx on a different server
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i "23i\\\tadd_header X-Served-By $(cat /etc/hostname);" /etc/nginx/sites-available/default
echo "Holberton School" | sudo tee /usr/share/nginx/html/index.html
sudo service nginx restart