#!/usr/bin/env bash
# This script will display a string 10 times modifying the 9th position to print "Hi"
i=1
while [ $i -le 10 ]
do
    echo "Holberton School"
    if [ $i -eq 9 ]
    then
	echo "Hi"
    fi
    let i=i+1
done
