#!/usr/bin/env bash
# run nginx as nginx user
sudo pkill apache2
chmod +r /etc/nginx/nginx.conf
sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sed -i 's/#user.*/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart